### ISSUE TITLE
Kill electron process

### ISSUE THREAD

**Issue by arthur-parmentier** [yuichkun/n4m-posenet#3]
Hi,

It looks like the electron process is not killed everytime, in case we loose focus on the electron window. Ideally, we should find a way to garantee it is killed, other than doing it manually. I am working on windows.

**Comment by yuichkun** [comment]
Hmm, OK I'll dig into it.

Since I do not own a Windows machine, it'll be a BIG help if you could provide:

- Console logs (of Max/node.debug) of when it happened
- Max version
- Brief computer spec (CPU/Memory etc.)
- And If there's a certain process to reproduce the case, please describe

Thank you!

**Comment by arthur-parmentier** [comment]
Nice!

Let me help you as much as I can.

First: on one of your fork, you can see one pull request that tries to kill the process when the windows are closed https://github.com/billythemusical/n4m-posenet-for-dummies/pull/2/commits/35ccdae3c3c5b48f17c15c5591202f97f982027b

I'll come back to you shortly with more details

**Comment by arthur-parmentier** [comment]
After testing, it looks like the pull request mentionned above solves the problem!

**Comment by yuichkun** [comment]
Hi @arthur-parmentier , sorry for not being able to react to a lot of the issues/comments you submitted a while ago.

As for the hanging process problem, I took the advice and put the clean up code in this source code as well.

Big thanks to @sayingu 🙏  !!

**Comment by yuichkun** [comment]
By the way, as you may have already noticed I'm such a lazy dumb person. 

So, if there're some bugs or feature suggestion, and if only you (or anyone) are willing to commit to the project, you are more than welcome to send PRs here 👍 
I'll try to keep updating as much as I can too tough!
