### ISSUE TITLE
"this browser does not support video capture,or this device does not have a camera" 

### ISSUE THREAD

**Issue by salem1loves1u** [yuichkun/n4m-posenet#6]
**Hi**!
NPM dependencies installation works great, although I have an issue with the PoseNet wrap inside Electron it launches the popup window then reads "Loading the model..." which it then just displays this error:

> "this browser does not support video capture,or this device does not have a camera"

Unsure of the cause but maybe you could give some info on some changes to let it run on localhost in chrome natively or something of that nature?

Thank-you! 
Look forward to hearing back from you.

**Salem**

**Comment by arthur-parmentier** [comment]
It looks like this problem is because your default camera is being used by an other process or not recognized when you are launching the script.

Do your webcam work with other programs? Can you make sure the camera is not used in other processes?

**Comment by yuichkun** [comment]
Yes, as Arthur says, I think it raises when the program tries to list the available device and finds none.

It sometimes happens on my computer too, for example when I'm using my MacBook in clamshell mode (in other words, the camera is not available).

The solution is simple: make sure that your **OS** is able to find at least one camera device.
If you are a mac user, one quick check you could do is to launch the built-in Photo Booth app.

Hope it helps!

I'm closing this issue now, but feel free to reopen if it still happens.
